FROM jruby:10.1.0.0-jdk25

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y git gcc

WORKDIR /app

COPY Gemfile* excluded_gems.txt ./

RUN gem install bundler -v '4.0.13'

# Pre-install ruby-maven (includes ruby-maven-libs) to avoid race conditions
# and ensure maven/ruby/maven is available for post-install hooks of other gems
RUN gem install ruby-maven

RUN bundle install --jobs 4

COPY . .

EXPOSE 3000

CMD (echo "local-build `date "+%Y-%m-%d_%H-%M-%S"`") > /app/build_version && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0
