FROM jruby:9.2.11.1

WORKDIR /app

COPY Gemfile* ./

RUN gem install bundler -v '2.1.4'

RUN bundle install --jobs 4

COPY . .

EXPOSE 3000

CMD (echo "local-build `date "+%Y-%m-%d_%H-%M-%S"`") > /app/build_version && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0