FROM jruby:10.0.3.0-jdk25

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y git gcc

WORKDIR /app

COPY Gemfile* ./

RUN gem install bundler -v '4.0.6'

RUN bundle install --jobs 4

COPY . .

EXPOSE 3000

CMD (echo "local-build `date "+%Y-%m-%d_%H-%M-%S"`") > /app/build_version && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0
