# Build and test MovexCdc application
# Requires:
#  - prebuilt database image
#  - kafka-jruby image built from /docker/kafka-jruby

# Dockerfile for image is located in movex-cdc/docker/kafka-jruby
image: registry.gitlab.com/osp-silver/oss/movex-cdc/kafka-jruby:9.3.8.0-jdk19

variables:
  RAILS_MAX_THREADS: 100
  CI_DEBUG_SERVICES: trace
  KAFKA_SEED_BROKER: localhost:9092
  TEMP_DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-ci-temp
  PODMAN: podman --events-backend=file --storage-driver=vfs --cgroup-manager=cgroupfs


# Separate stages because pending jobs get stuck after one hour (hard limit)
stages:
  - build
  - deploy

generate_asciidoc:
  stage: build
  script:
    - gem install --no-doc asciidoctor
    - asciidoctor -o doc/movex-cdc.html doc/movex-cdc.adoc
    - asciidoctor -o doc/movex-cdc_demo.html doc/movex-cdc_demo.adoc
    - gem install --no-doc asciidoctor-pdf
    - asciidoctor-pdf -o doc/movex-cdc.pdf doc/movex-cdc.adoc
  artifacts:
    paths:
      - doc/movex-cdc.html
      - doc/movex-cdc_demo.html
      - doc/images/
      - doc/movex-cdc.pdf


# Deploy the static site to GitLab Pages, but only for master branch
pages:
  stage: deploy
  only:
    refs:
      - master
  script:
    - cp doc/movex-cdc.html public/
    - cp -r doc/images public/
    - cp doc/movex-cdc.pdf public/
    - cp doc/movex-cdc_demo.html public/
    - cp doc/google70fcb57bf7ac9cbe.html public/
    - cp doc/sitemap.xml public/
  artifacts:
    paths:
      - public/movex-cdc.pdf
      - public/movex-cdc.html
      - public/movex-cdc_demo.html
      - public/google70fcb57bf7ac9cbe.html
      - public/sitemap.xml
      - public/images/

