# currently not used, see Dockerfile-kafka-jruby-oracle
# Build Docker image based on jRuby with both zookeeper and kafka
# for usage as default image for whole CI pipeline for MOVEX CDC
# Peter Ramm, 2020-03-17

# Usage:
# Build image:      > docker build -f Dockerfile-kafka-jruby-debian --no-cache -t git.osp-dd.de:5005/main/movex-cdc/kafka-jruby:9.2.15.0-jre11 .
# Run container:    > docker run  git.osp-dd.de:5005/main/movex-cdc/kafka-jruby:9.2.15.0-jre11
# Use

ARG JRUBY_VERSION=9.2.15.0

FROM jruby:$JRUBY_VERSION-jre11

MAINTAINER Peter.Ramm@ottogroup.com

ARG KAFKA_VERSION=2.6.0
ARG SCALA_VERSION=2.13
ENV JRUBY_VERSION=$JRUBY_VERSION
ENV KAFKA_VERSION=$KAFKA_VERSION
ENV SCALA_VERSION=$SCALA_VERSION
ENV KAFKA_HOME=/opt/kafka

#EXPOSE 2181/tcp 9092/tcp

# RUN-Steps:
# - update Debian system
# - install ps
# - install podman
# - install Kafka
RUN  apt-get update && \
     apt-get -y upgrade && \
     apt-get install -y procps && \
     echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && \
     curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key | apt-key add - && \
     apt-get update -qq && \
     apt-get -qq -y install podman && \
     wget "https://mirror.softaculous.com/apache/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz" -O /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && \
     cd /opt && tar xvf /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && \
     ln -s kafka_${SCALA_VERSION}-${KAFKA_VERSION} ${KAFKA_HOME} && \
     sed -i 's|^log.dirs=.*$|log.dirs=/var/lib/kafka|' /opt/kafka/config/server.properties

# Without own volume for ontime usage in CI pipeline
#VOLUME /var/lib/kafka

COPY    run-kafka-jruby.sh start-kafka.sh /opt/

# use bracket syntax to ensure run-kafka-jruby.sh runs with PID 1 and receives SIGTERM signal
CMD ["/opt/run-kafka-jruby.sh"]
