class CreateEventLogs < ActiveRecord::Migration[6.0]
  def up
    case Trixx::Application.config.trixx_db_type
    when 'ORACLE' then
      EventLog.connection.execute("\
      CREATE TABLE Event_Logs (
        ID          NUMBER(38),
        Schema_ID   NUMBER(38),
        Table_ID    NUMBER(38),
        Payload     CLOB,
        Created_At  TIMESTAMP(6)
        )
        PCTFREE 0
        INITRANS 16
        PARTITION BY RANGE (Created_At) INTERVAL( NUMTODSINTERVAL(10,'MINUTE'))
        ( PARTITION MIN VALUES LESS THAN (TO_DATE(' 2000-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) )
      ")
      # Sequence Event_Logs_Seq is generated by migration automatically
    when 'SQLITE' then
      create_table :event_logs do |t|
        t.references  :schema,      null: false
        t.references  :table,       null:false
        t.text        :payload,     null: false
        t.timestamp   :created_at,  null: false,  comment: 'Record creation timestamp'
      end
    end
  end

  def down
    drop_table(:event_logs)
  end
end
