# Build Docker image with both zookeeper and kafka, based on idea of Martin Nowack
# for usage as single node cluster (non-persistent)
# Peter Ramm, 2020-03-09

# Usage:
# Build image:      > docker build -f Dockerfile-kafka-compact -t registry.gitlab.com/osp-silver/oss/movex-cdc/kafka-compact:3.7.0 .
# Run container:    > docker run  -p 2181:2181 -p 9092:9092 -e KAFKA_ADVERTISED_LISTENERS=LISTENER_EXT://localhost:9092,LISTENER_INT://localhost:9093 registry.gitlab.com/osp-silver/oss/movex-cdc/kafka-compact:3.7.0
# Use


# FROM openjdk:17-jdk-alpine
FROM eclipse-temurin:21

MAINTAINER Peter.Ramm@ottogroup.com

# 3.5.0 has problems working with single node cluster
ARG KAFKA_VERSION=3.7.0
ARG SCALA_VERSION=2.13
ENV KAFKA_VERSION=$KAFKA_VERSION
ENV SCALA_VERSION=$SCALA_VERSION

# generate unique id by default
ENV BROKER_ID=-1
ENV KAFKA_HOME=/opt/kafka
ENV KAFKA_LISTENERS=LISTENER_EXT://0.0.0.0:9092,LISTENER_INT://0.0.0.0:9093
ENV KAFKA_ADVERTISED_LISTENERS=LISTENER_EXT://localhost:9092,LISTENER_INT://localhost:9093
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_EXT:PLAINTEXT,LISTENER_INT:PLAINTEXT
ENV KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
EXPOSE 2181/tcp 9092/tcp

RUN apt install -y wget tar gzip bash

RUN wget "https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz" -O /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz

RUN ls -l /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz
RUN cd /opt && tar xvf /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && \
    ln -s kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka && \
    sed -i 's|^log.dirs=.*$|log.dirs=/var/lib/kafka|' /opt/kafka/config/server.properties

COPY    start_kafka.sh /opt/

# Ensure container environment is used at container run time
CMD ["/opt/start_kafka.sh"]
